cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.jest-cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks: "https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN"

language: php

dist: trusty

services:
  - mysql
  - docker

addons:
  apt:
    packages:
      - libxml2-utils

branches:
  only:
    - master
    - develop
    - /^\d+\.\d+$/

env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - COVERALLS_PARALLEL=true

before_install:
  - nvm install
  - nvm use

install:
  - npm install
  - composer install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - export DIFF_HEAD=HEAD
  - source "$DEV_LIB_PATH/travis.install.sh"

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist."

script:
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

jobs:
  fast_finish: true
  include:
    - stage: lint
      name: Lint (PHP, JavaScript, and configuration files)
      php: "7.4"
      env: WP_VERSION=latest DEV_LIB_ONLY=xmllint,phpsyntax
      script:
        - source "$DEV_LIB_PATH/travis.script.sh"
        - npm run lint

    - stage: test
      name: E2E tests with Docker (7.4, WordPress latest, with code coverage)
      php: "7.4"
      env: NODE_ENV=teste2e
      before_install:
        - nvm install
        - nvm use
        - unset PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
      before_script:
        - sudo service mysql stop
        - echo "Running E2E tests with code coverage ..."
      script:
        - npm run env:start
        - npm run wp -- wp core install --title=WordPress --admin_user=admin --admin_password=password --admin_email=admin@example.com --skip-email --url=http://localhost:8088 --quiet
        - npm run wp -- wp plugin activate material-theme-builder
        - npm run build:js
        - npm run test:e2e:coveralls

    - name: JS unit tests (7.4, WordPress latest, with code coverage)
      php: "7.4"
      before_script:
        - echo "Running JS unit tests with code coverage ..."
      script:
        - npm run build:js
        - npm run test:js:coveralls

    - name: JS and E2E tests with Docker (7.4, WordPress 5.3.2)
      php: "7.4"
      env: WP_VERSION=5.3.2 DEV_LIB_ONLY=phpunit
      before_install:
        - nvm install
        - nvm use
        - unset PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
      before_script:
        - sudo service mysql stop
        - echo "Running JS and E2E tests ..."
      script:
        - npm run env:start
        - npm run wp -- wp core install --title=WordPress --admin_user=admin --admin_password=password --admin_email=admin@example.com --skip-email --url=http://localhost:8088 --quiet
        - npm run wp -- wp plugin activate material-theme-builder
        - npm run build:js
        - npm run test:js
        - npm run test:e2e

    - name: JS and E2E tests with Docker (7.4, WordPress 5.2)
      php: "7.4"
      env: WP_VERSION=5.2 DEV_LIB_ONLY=phpunit
      before_install:
        - nvm install
        - nvm use
        - unset PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
      before_script:
        - sudo service mysql stop
        - echo "Running JS and E2E tests ..."
      script:
        - npm run env:start
        - npm run wp -- wp core install --title=WordPress --admin_user=admin --admin_password=password --admin_email=admin@example.com --skip-email --url=http://localhost:8088 --quiet
        - npm run wp -- wp plugin activate material-theme-builder
        - npm run build:js
        - npm run test:js
        - npm run test:e2e

    - name: PHP unit tests (7.4, WordPress latest, with code coverage)
      php: "7.4"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit,coverage
      before_script:
        - echo "Running PHP unit tests with code coverage ..."
      script:
        - source "$DEV_LIB_PATH/travis.script.sh"

    - name: PHP unit tests (7.3, WordPress latest)
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit

    - name: PHP unit tests (7.2, WordPress latest)
      php: "7.2"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit

    - name: PHP unit tests (7.1, WordPress latest)
      php: "7.1"
      env: WP_VERSION=latest DEV_LIB_ONLY=phpunit

    - name: PHP unit tests (7.0, WordPress 5.1)
      php: "7.0"
      env: WP_VERSION=5.1 DEV_LIB_ONLY=phpunit

    - name: PHP unit tests (5.6, WordPress 5.0)
      php: "5.6"
      env: WP_VERSION=5.0 DEV_LIB_ONLY=phpunit

    - name: PHP unit tests (7.4, WordPress trunk)
      php: "7.4"
      env: WP_VERSION=trunk DEV_LIB_ONLY=phpunit

    - name: PHP unit tests (5.6, WordPress trunk)
      php: "5.6"
      env: WP_VERSION=trunk DEV_LIB_ONLY=phpunit

    - stage: deploy to staging
      if: (NOT type IN (pull_request))
      script: skip
      deploy:
        skip_cleanup: true
        # deploy builds in develop to the pantheon dev environment
        provider: script
        script: bash bin/deploy.sh
        on:
          branch: develop
